Repository woorifisa-projects/HaeDal, pull requests merged in 2023-08, with the labels that each got.

#7 Chore : 프로젝트 초기설정
  .idea/.gitignore
  .idea/HaeDal.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/haedal/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/haedal/backend/BackendApplicationTests.java
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/.vscode/extensions.json
  frontend/README.md
  frontend/cypress.config.js
  frontend/cypress/e2e/example.cy.js
  frontend/cypress/e2e/jsconfig.json
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/components/HelloWorld.vue
  frontend/src/components/TheWelcome.vue
  frontend/src/components/WelcomeItem.vue
  frontend/src/components/__tests__/HelloWorld.spec.js
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/stores/counter.js
  frontend/src/views/AboutView.vue
  frontend/src/views/HomeView.vue
  frontend/vite.config.js
  frontend/vitest.config.js
Labels: chore

#9 Chore : 백엔드 패키지 구조 설정
  .idea/inspectionProfiles/Project_Default.xml
  backend/src/main/java/com/haedal/backend/admin/controller/AdminController.java
  backend/src/main/java/com/haedal/backend/admin/dto/request/AdminRequest.java
  backend/src/main/java/com/haedal/backend/admin/dto/response/AdminResponse.java
  backend/src/main/java/com/haedal/backend/admin/model/Admin.java
  backend/src/main/java/com/haedal/backend/admin/repository/AdminRepository.java
  backend/src/main/java/com/haedal/backend/admin/service/AdminService.java
  backend/src/main/java/com/haedal/backend/auth/controller/AuthController.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/AuthRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/AuthResponse.java
  backend/src/main/java/com/haedal/backend/auth/model/Auth.java
  backend/src/main/java/com/haedal/backend/common/service/CrudService.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/request/ProductRequest.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/ProductService.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/request/ProfileRequest.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/model/User.java
  backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
Labels: chore, 백엔드

#12 Feat : 프로필 Api
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/model/ServicePurpose.java
  backend/src/main/java/com/haedal/backend/profile/model/User.java
  backend/src/main/java/com/haedal/backend/profile/model/UserAgeGroup.java
  backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
  backend/src/main/java/com/haedal/backend/profile/service/CrudService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  backend/src/main/resources/application.properties
Labels: 기능 추가, 백엔드

#13 Feat : Product패키지 model 생성
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/product/model/Tag.java
Labels: 백엔드

#15 Refactor : DB 리팩토링
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/model/Deposit.java
  backend/src/main/java/com/haedal/backend/product/model/InstallmentSavings.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/profile/model/Account.java
  backend/src/main/java/com/haedal/backend/profile/model/User.java
  backend/src/test/java/com/haedal/backend/product/ProductControllerTest.java
Labels: 리팩토링

#17 Refactor : DB 리팩토링
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/model/Account.java
  backend/src/main/java/com/haedal/backend/profile/model/User.java
  backend/src/main/resources/application.properties
Labels: 리팩토링

#20 Feature : 전체상품 조회, 필터링 기능 구현
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/request/ProductRequest.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/CrudService.java
  backend/src/main/java/com/haedal/backend/product/service/ProductService.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  backend/src/main/resources/application.properties
  frontend/package-lock.json
  frontend/package.json
Labels: 기능 추가, 백엔드

#21 Feat : 회원가입 및 로그인 백엔드 api 구현
  backend/build.gradle
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/AuthController.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/UserDto.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/AuthRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserLoginRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserRegisterRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/AuthResponse.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserLoginResponse.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserRegisterResponse.java
  backend/src/main/java/com/haedal/backend/auth/model/Auth.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/auth/repository/UserRepository.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/auth/util/JwtUtil.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  backend/src/main/resources/application.properties
Labels: 기능 추가, 백엔드

#23 feature : 상품 키워드 검색 기능 추가
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/ProductService.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  frontend/src/App.vue
  frontend/src/router/index.js
  frontend/src/views/ProductList.vue
Labels: 기능 추가, 백엔드

#27 Refactor : DB재설계 - Product테이블 통합
  backend/src/main/java/com/haedal/backend/product/model/Deposit.java
  backend/src/main/java/com/haedal/backend/product/model/InstallmentSavings.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
Labels: 리팩토링, 백엔드

#29 Refactor : 접근권한 허용 - /products/
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
Labels: 리팩토링, 백엔드

#32 Style : 헤더,로그인,회원가입화면 구현
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/Header.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
Labels: UI, 프론트엔드

#36 refactor : 제품 이름 검색 기능 수정
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
Labels: 리팩토링, 백엔드

#38 Refactor : 상품탭 필터링 기능 구현
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
Labels: 리팩토링

#43 Style : 로그인,회원가입 화면 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/Header.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
Labels: UI, 프론트엔드

#44 feature : 구독 model 수정, 패키지 설정, controller 기능 초안 설정
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/product/model/Deposit.java
  backend/src/main/java/com/haedal/backend/product/model/InstallmentSavings.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/SubscribeResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/CrudService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
Labels: 기능 추가, 리팩토링, 백엔드

#46 reafctor: subscribe 구독 로직 작성
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/ProductService.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/SubscribeResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, 백엔드

#51 Refactor : Product DB 수정 - 예금,적금 테이블 삭제 후 통합테이블 구현
  backend/src/main/java/com/haedal/backend/product/model/Product.java
Labels: 리팩토링, 백엔드

#53 Feature : 로그인 시 로그인 유저 데이터 조회하는 api 개발
  .idea/modules/com.haedal.backend.main.iml
  backend/src/main/java/com/haedal/backend/auth/config/JwtFilter.java
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/config/WebConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserDataRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserDataResponse.java
  backend/src/main/java/com/haedal/backend/auth/repository/UserRepository.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/auth/util/JwtUtil.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  frontend/src/views/Header.vue
Labels: 기능 추가, 프론트엔드, 백엔드

#56 style : 상품 검색, 필터링 화면 구현, 연결
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/config/WebConfig.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/package.json
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: UI, 프론트엔드, 백엔드

#58 Feature : 회원가입, 로그인 service 단계 테스트 코드 작성
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserRegisterRequest.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/auth/service/UserServiceTest.java
Labels: 기능 추가, Test, 백엔드

#62 refactor : 예금 적금 분기처리
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  frontend/src/layouts/default/Default.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#65 Refactor : 깃허브 충돌 코드 수정 및 병합
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  frontend/src/router/index.js
  frontend/src/store/app.js
  frontend/src/views/Header.vue
  frontend/src/views/LoginViewTest.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/SignUpView.vue
  frontend/src/views/UserProfileEdit.vue
Labels: 리팩토링

#66 syle : 추천 상품 페이지 ui 구현
  frontend/src/router/index.js
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SubscribeI.vue
Labels: 기능 추가, UI, 프론트엔드

#67 Feature: 자산별, 이용목적별, 연령대별 추천상품 조회 기능 추가
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/ProductService.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
Labels: 기능 추가, 백엔드

#69 fix : 상품 추천 필터 api 수정
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
Labels: 리팩토링, 백엔드

#71 refactor : get요청 nullPointException 해결, serviceImp 수정
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/views/RecommendedProduct.vue
Labels: 리팩토링, 백엔드

#72 Refactor : git ignore 추가
  backend/.gitignore
  backend/src/main/resources/application.properties
Labels: 리팩토링

#74 fix : userService 테스트코드 error 수정
  backend/src/test/java/com/haedal/backend/auth/service/UserServiceTest.java
Labels: 버그발생!, 백엔드

#77 Refactor : 기존 프로필 정보 조회 및 개인정보 수정 api 리팩토링
  .idea/compiler.xml
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserDataRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserIdCheckRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserUpdateRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserDataResponse.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserIdCheckResponse.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserUpdateResponse.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  frontend/src/assets/img/HaeDalLogo.png
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/Header.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/LoginViewTest.vue
  frontend/src/views/MainPage.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/ProfileMain.vue
  frontend/src/views/SecuritySetting.vue
  frontend/src/views/SignUpView.vue
  frontend/src/views/UserProfileEdit.vue
Labels: 기능 추가, 리팩토링, 프론트엔드, 백엔드

#78 Feature: 추천상품 조회기능 API 기능 추가 및 수정
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/profile/model/UserAgeGroup.java
  backend/src/main/resources/application.properties
Labels: 기능 추가, 리팩토링, 프론트엔드

#80 Refactor : 회원상품가입 api 로그인정보와 연동하여 개발 및 화면 요청 부분 수정
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/LoginView.vue
  frontend/src/views/MainPage.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SignUpView.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#81 Refactor : 회원상품가입 api 로그인정보와 연동하여 개발 및 화면 요청 부분 수정
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/router/index.js
  frontend/src/views/ForSecuritySetting.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#85 refactor : recommendedProduct API connection
  frontend/src/views/RecommendedProduct.vue
Labels: 프론트엔드

#86 refactor : 상품 조회 url 변경, ui 수정, 신청 정보 추가
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/assets/img/success.jpg
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/LoginView.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/SubscribeSuccess.vue
Labels: 기능 추가, 리팩토링, UI, 프론트엔드, 백엔드

#87 Refactor : 시큐리티 인증인가 부분 수정 및 개인정보 창 접속시 비밀번호 검증 창 및 api 추가
  backend/src/main/java/com/haedal/backend/auth/config/JwtFilter.java
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserLoginRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserPasswordCheckRequest.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/ChangePassword.vue
  frontend/src/views/ForSecuritySetting.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/Portfolio.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#92 style : 상품 관련 ui 정리
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/router/index.js
  frontend/src/views/MainPage.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/SubscribeSuccess.vue
  frontend/src/views/UserProfileEdit.vue
Labels: UI, 프론트엔드

#93 [Feature] 포트폴리오 api 개발 및 상품 조회 화면 추가
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/PortfolioResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/CrudService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/router/index.js
  frontend/src/views/LoginView.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeIforShow.vue
  frontend/src/views/UserProfileEdit.vue
Labels: 기능 추가, 리팩토링, 프론트엔드, 백엔드

#96 refactor : controller의 dto 프로세스 리팩토링
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/router/index.js
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, 백엔드

#98 feature : status 칼럼 추가, 관련 로직 수정, 상품추천 인증 설정 추가
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
Labels: 기능 추가, 프론트엔드, 백엔드
