Repository woorifisa-projects/HaeDal, pull requests merged in 2023-09, with the labels that each got.

#100 style : 에러 화면 제작, 오늘의 추천 상품 추가
  frontend/src/assets/img/exception.png
  frontend/src/assets/img/main-image1.png
  frontend/src/router/index.js
  frontend/src/views/Error.vue
  frontend/src/views/MainPage.vue
Labels: UI, 프론트엔드

#102 feature: 찜기능 추가
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/Dibs/dto/request/AdminRequest.java
  backend/src/main/java/com/haedal/backend/Dibs/dto/response/DibsResponse.java
  backend/src/main/java/com/haedal/backend/Dibs/model/Dibs.java
  backend/src/main/java/com/haedal/backend/Dibs/repository/DibsRepository.java
  backend/src/main/java/com/haedal/backend/Dibs/service/DibsService.java
  backend/src/main/java/com/haedal/backend/Dibs/service/DibsServiceImp.java
  backend/src/main/java/com/haedal/backend/admin/controller/AdminController.java
  backend/src/main/java/com/haedal/backend/admin/dto/request/AdminRequest.java
  backend/src/main/java/com/haedal/backend/admin/dto/response/AdminResponse.java
  backend/src/main/java/com/haedal/backend/admin/model/Admin.java
  backend/src/main/java/com/haedal/backend/admin/repository/AdminRepository.java
  backend/src/main/java/com/haedal/backend/admin/service/AdminService.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/assets/img/favorite.png
  frontend/src/assets/img/favorite_border.png
  frontend/src/views/MainPage.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
Labels: UI, 프론트엔드

#103 Feature 포트폴리오 화면 정보 추가에 필요한 api개발 및 화면 수정을 진행한다
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/PortfolioResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/index.html
  frontend/public/faviconHaeDal.ico
  frontend/src/api/index.js
  frontend/src/api/modules/getApi.js
  frontend/src/api/modules/index.js
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/layouts/default/Footer.vue
  frontend/src/views/Header.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/UserProfileEdit.vue
Labels: 기능 추가, 리팩토링, 백엔드

#107 Feature : 포트폴리오 화면 개발, 회원탈퇴 화면 통신 개발, 아이디 중복체크 api 프론트 연결, 비밀번호 변경 api 프론트 연결
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/repository/UserRepository.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
  frontend/src/router/index.js
  frontend/src/views/ChangePassword.vue
  frontend/src/views/ForPasswordChange.vue
  frontend/src/views/ForSecuritySetting.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/SecurityMain.vue
  frontend/src/views/SignUpView.vue
  frontend/src/views/UserLeave.vue
Labels: 기능 추가, 프론트엔드, 백엔드

#106 refactor : 상품 상세 페이지와 상품 가입 페이지 분리, 찜 기능 추가
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/layouts/default/Footer.vue
  frontend/src/views/Error.vue
  frontend/src/views/MainPage.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 기능 추가, 리팩토링, 프론트엔드, 백엔드

#109 refactor : 자산별 상품 추천 기준 추가
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
Labels: 리팩토링

#112 [Refactor] 마이페이지, FK 외래키 설정 기능 개선, UI 개선
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/Dibs/model/Dibs.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/Footer.vue
  frontend/src/views/ForPasswordChange.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SecurityMain.vue
  frontend/src/views/SecuritySetting.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/SubscribeIforShow.vue
  frontend/src/views/UserLeave.vue
  frontend/src/views/UserProfileEdit.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#113 Feature 포트폴리오 내에서 좋아요 표시한 금융상품과 기존 가입금융상품 금액순서대로 변경
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/Dibs/model/Dibs.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/PortfolioResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/components/PortfolioHeader.vue
  frontend/src/router/index.js
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
Labels: 기능 추가, 프론트엔드, 백엔드

#116 Refactor : 포트폴리오 화면 클릭시 router로 이동부분 추가
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
Labels: 리팩토링, 프론트엔드

#117 refactor : 로그 기능 추가
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/Dibs/model/Dibs.java
  backend/src/main/java/com/haedal/backend/Dibs/repository/DibsRepository.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/log/model/Log.java
  backend/src/main/java/com/haedal/backend/log/model/LogType.java
  backend/src/main/java/com/haedal/backend/log/repository/LogRepository.java
  backend/src/main/java/com/haedal/backend/log/service/LogService.java
  backend/src/main/java/com/haedal/backend/log/service/LogServiceImp.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/PortfolioResponse.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/views/LoginView.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SignUpView.vue
Labels: 기능 추가, 프론트엔드, 백엔드

#119 Refactor : 로그 수정, 프론트 예외 페이지 연결
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  frontend/src/layouts/default/Footer.vue
  frontend/src/views/Error.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeIforShow.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#122 [Feature] 상품 구독시 로그 저장 기능 추가, 상품 중복 가입 통제
  backend/src/main/java/com/haedal/backend/log/model/LogType.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/router/index.js
  frontend/src/views/SubscribeI.vue
Labels: 기능 추가, 리팩토링, 백엔드

#123 Feature : HTTPS를 적용한다
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/LoginView.vue
Labels: 기능 추가

#126 Refactor : 유저 회원탈퇴 관련 api 수정, 로그인시 회원상태에 따라 분기처리
  backend/src/main/java/com/haedal/backend/auth/config/JwtFilter.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/LoginView.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#128 Refactor : 구독 예외 처리
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/log/model/Log.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, 프론트엔드, 백엔드

#129 Feat : SMS 전송 api를 위한 폴더 생성 및 api구현
  backend/build.gradle
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/sms/controller/SmsController.java
  backend/src/main/java/com/haedal/backend/sms/dto/MessageDTO.java
  backend/src/main/java/com/haedal/backend/sms/dto/request/SmsRequestDTO.java
  backend/src/main/java/com/haedal/backend/sms/dto/response/SmsResponseDTO.java
  backend/src/main/java/com/haedal/backend/sms/service/SmsService.java
  frontend/src/views/MainPage.vue
Labels: 기능 추가, 백엔드

#131 Feat : SMS 전송 api를 위한 폴더 생성 및 api구현
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/UserDto.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserRegisterResponse.java
  backend/src/main/java/com/haedal/backend/sms/controller/SmsController.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/common/ControllerTest.java
Labels: 기능 추가, 백엔드

#133 Feature RestDocs 의존성 설치 및 공통TestCode 추가 및 UserController Test코드 작성
  backend/build.gradle
  backend/src/docs/asciidoc/auth.adoc
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/response/UserLoginResponse.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/sms/dto/MessageDTO.java
  backend/src/main/resources/static/auth.html
  backend/src/main/resources/static/index.html
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/common/ControllerTest.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/LoginView.vue
Labels: chore, Test, 백엔드

#137 feature : sms 기능 구체화, 에러 해결
  backend/src/main/java/com/haedal/backend/log/repository/LogRepository.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/sms/controller/SmsController.java
  backend/src/main/java/com/haedal/backend/subscribe/dto/response/PortfolioResponse.java
  frontend/src/layouts/default/AppBar.vue
Labels: 기능 추가, 프론트엔드, 백엔드

#139 refactor : 고객 가입시 상태 true로 설정
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  frontend/src/views/LoginView.vue
Labels: 리팩토링, 백엔드

#142 Fix : subscribe 요건 추가
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/assets/img/banner-1.png
  frontend/src/assets/img/leave.jpg
  frontend/src/assets/img/main-image1.png
  frontend/src/assets/img/profile.png
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Footer.vue
  frontend/src/router/index.js
  frontend/src/views/MainPage.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/UserLeave.vue
Labels: UI, 프론트엔드, 백엔드

#143 Refactor 유저컨트롤러 테스트 추가 및 유저 로그인 시 예외처리 프론트 연동
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/exception/InactiveUserException.java
  backend/src/main/java/com/haedal/backend/auth/exception/InvalidIdException.java
  backend/src/main/java/com/haedal/backend/auth/exception/InvalidPasswordException.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/store/app.js
  frontend/src/views/LoginView.vue
Labels: 리팩토링, Test, 프론트엔드, 백엔드

#145 style : 상품 목록 스타일 수정
  frontend/src/views/ProductList.vue
Labels: UI

#148 Feature 포트폴리오 내에서 구독한 상품 해지 api와 화면을 개발한다
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeIforShow.vue
Labels: 기능 추가, 프론트엔드, 백엔드

#150 Feat : appbar 로그인만료시간 체크추가
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/common/ControllerTest.java
  frontend/src/layouts/default/AppBar.vue
Labels: 기능 추가, 프론트엔드

#152 bug : authentication 테스트코드에서 사용시 null으로 전달되는 오류 수정
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/model/User.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/common/ControllerTest.java
Labels: 버그발생!, Test

#157 Refactor : 로그아웃 관련 api요청 삭제
  frontend/src/layouts/default/AppBar.vue
Labels: 리팩토링, 프론트엔드

#160 feat : security 설정, @responsestatus로 예외코드 반환설정, UserControllerTest완료, 구독일자별 수익율 수정, jpql수정
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserLoginRequest.java
  backend/src/main/java/com/haedal/backend/auth/exception/InactiveUserException.java
  backend/src/main/java/com/haedal/backend/auth/exception/InvalidIdException.java
  backend/src/main/java/com/haedal/backend/auth/exception/InvalidPasswordException.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  frontend/src/views/PortfolioDays.vue
Labels: 버그발생!, 기능 추가, 리팩토링, 프론트엔드, 백엔드

#162 refactor : 상품구독해제 시 jpql 쿼리문 명확하게 리팩토링 진행
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
Labels: 리팩토링, 백엔드

#164 feature : 구독, 찜 기능 테스트코드 작성
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/Dibs/model/Dibs.java
  backend/src/main/java/com/haedal/backend/Dibs/repository/DibsRepository.java
  backend/src/main/java/com/haedal/backend/Dibs/service/DibsService.java
  backend/src/main/java/com/haedal/backend/Dibs/service/DibsServiceImp.java
  backend/src/main/java/com/haedal/backend/log/model/Log.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/service/ProductService.java
  backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
  backend/src/test/java/com/haedal/backend/Dibs/controller/DibsControllerTest.java
  backend/src/test/java/com/haedal/backend/common/ControllerTest.java
  backend/src/test/java/com/haedal/backend/subscribe/controller/SubscribeControllerTest.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/SubscribeIforShow.vue
Labels: 리팩토링, Test, 프론트엔드, 백엔드

#166 Feature : 회원가입시 비밀번호 동일 여부 확인
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
Labels: 프론트엔드

#168 feat : profile 단위테스트 코드 작성 및 ProfileController 코드 리팩토링
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserPasswordCheckRequest.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserUpdateRequest.java
  backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
  backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
  backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/product/ProductControllerTest.java
  backend/src/test/java/com/haedal/backend/profile/controller/ProfileControllerTest.java
Labels: 리팩토링, Test

#170 Style : UI 수정
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  frontend/src/assets/img/main-image1.png
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MainPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SignUpView.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/SubscribeIforShow.vue
  frontend/src/views/UserLeave.vue
  frontend/src/views/UserProfileEdit.vue
Labels: UI

#173 refactor : 회원가입-UI수정, ID중복체크 실패시 예외모달창 추가
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  frontend/src/router/index.js
  frontend/src/views/ForPasswordChange.vue
  frontend/src/views/ForSecuritySetting.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
Labels: 리팩토링, 프론트엔드

#175 fix : 비밀번호 visible이벤트 발생시 바로 출력안되는 문제 수정
  frontend/src/views/LoginView.vue
  frontend/src/views/SignUpView.vue
Labels: 프론트엔드

#177 style : 배너 이미지 추가
  frontend/src/assets/img/banner-1.png
  frontend/src/assets/img/banner-2.png
  frontend/src/assets/img/banner-3.png
  frontend/src/views/MainPage.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SignUpView.vue
Labels: UI

#179 style : 마이페이지 스타일 수정
  frontend/src/assets/img/banner-3.png
  frontend/src/views/MainPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SignUpView.vue
Labels: UI

#182 fix : 상세페이지 찜기능 오류 해결
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 버그발생!, 프론트엔드

#184 refactor : 검색, 찜 기능 개선
  backend/src/main/java/com/haedal/backend/Dibs/controller/DibsController.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
  frontend/src/assets/img/banner-3.png
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, UI, 프론트엔드, 백엔드

#185 Refactor : ProductController, RecommendedController JUnit5 테스트 코드 작성 …
  backend/build.gradle
  backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/haedal/backend/auth/dto/request/UserRegisterRequest.java
  backend/src/main/java/com/haedal/backend/auth/service/UserService.java
  backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
  backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
  backend/src/main/java/com/haedal/backend/product/dto/request/ProductRequest.java
  backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/com/haedal/backend/product/model/Product.java
  backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
  backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
  backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
  backend/src/test/java/com/haedal/backend/common/ControllerTest.java
  backend/src/test/java/com/haedal/backend/product/ProductControllerTest.java
  backend/src/test/java/com/haedal/backend/product/RecommendedProductControllerTest.java
  frontend/src/views/ForPasswordChange.vue
Labels: 기능 추가, 리팩토링, 백엔드

#190 chore : chartJS 환경설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/Test.vue
Labels: chore, 프론트엔드

#193 style : 웹 최적화 관련사항 개선, UI 개선
  frontend/src/assets/img/banner-1.png
  frontend/src/assets/img/banner-3.png
  frontend/src/assets/img/haedal-mockup.png
  frontend/src/components/PortfolioHeader.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Footer.vue
  frontend/src/layouts/default/NoFooter.vue
  frontend/src/router/index.js
  frontend/src/views/MainPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/Test.vue
Labels: UI, 프론트엔드

#196 refactor : 로그인한사람만 찜요청보내도록 수정, 요청 접수 시 settimeout으로 중복 submit방지
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/ForSecuritySetting.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeI.vue
Labels: 리팩토링, 프론트엔드

#200 fix : 검색결과없을시 무한로딩되며 검색 막히는 버그 수정, 보안설정에서 취소 클릭시 이전페이지로 돌아가지않는 현상 수정,…
  frontend/src/components/PortfolioHeader.vue
  frontend/src/components/ProfileNavigationBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/ChartPortfolio.vue
  frontend/src/views/ForPasswordChange.vue
  frontend/src/views/MainPage.vue
  frontend/src/views/MyPage.vue
  frontend/src/views/Portfolio.vue
  frontend/src/views/PortfolioDays.vue
  frontend/src/views/Portfoliodibs.vue
  frontend/src/views/ProductList.vue
  frontend/src/views/RecommendedProduct.vue
  frontend/src/views/SignUpView.vue
  frontend/src/views/SubscribeD.vue
  frontend/src/views/SubscribeDforShow.vue
  frontend/src/views/SubscribeI.vue
  frontend/src/views/SubscribeIforShow.vue
  frontend/src/views/UserLeave.vue
  frontend/src/views/UserProfileEdit.vue
Labels: 버그발생!, 리팩토링, 프론트엔드
